# Generated by Django 5.2.1 on 2025-05-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('toll', 'Toll Tax'), ('fuel', 'Fuel'), ('food', 'Food'), ('police', 'Police/Bribe'), ('driver', 'Driver'), ('helper', 'Helper'), ('loading', 'Loading'), ('unloading', 'Unloading'), ('commission', 'Commission'), ('garage', 'Garage/Maintenance'), ('mechanic', 'Mechanic'), ('motorway_tax', 'Motorway Tax'), ('security', 'Security'), ('kaanta', 'Kaanta'), ('other', 'Other')], max_length=20),
        ),
    ]
