# Generated by Django 5.2.1 on 2025-05-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_expense_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuellog',
            name='last_odometer_reading',
            field=models.PositiveIntegerField(blank=True, help_text='Previous reading (auto-filled)', null=True),
        ),
        migrations.AddField(
            model_name='fuellog',
            name='odometer_reading',
            field=models.PositiveIntegerField(default=1, help_text="Truck's meter reading at time of fueling"),
            preserve_default=False,
        ),
    ]
